### ISSUE TITLE
Implement project page view

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/project-papers#35]
We need to create and implement multiple views that comprise the overall Project View of the web app, as shown in https://projects.invisionapp.com/freehand/document/UN0IwfDwq.

This includes:
- [ ] `ProjectSectionView` (https://github.com/NCEAS/metacatui/issues/815)
    - [x] `ProjectHomeView` (NCEAS/metacatui#824) 
    - [x] `ProjectMetricsView` (NCEAS/metacatui#823)
    - [x] `ProjectMembersView` (NCEAS/metacatui#825)
    - [ ] `ProjectVisualizationsView` (NCEAS/metacatui#826)
- [x] `ProjectHeaderView` (https://github.com/NCEAS/metacatui/issues/816)
- [x] `ProjectFiltersView` (https://github.com/NCEAS/metacatui/issues/817)
- [ ] `TOCView` (https://github.com/NCEAS/metacatui/issues/818)
- [x] `MapsView` (https://github.com/NCEAS/metacatui/issues/819)
- [ ] `MarkdownView` (https://github.com/NCEAS/metacatui/issues/820)
- [x] `ProjectMembersView` (https://github.com/NCEAS/metacatui/issues/821)
- [x] `ProjectLogosView` (https://github.com/NCEAS/metacatui/issues/822)
